# -*- coding: utf-8 -*-
"""Uts2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z77ZLtLywxoF_Y9LjL4AukKVebo1XM8e
"""

#uts2
#Nadia Alifiani Raissa Pansera ;21091397014 ; 2021B

import numpy as num

inputs = [[1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0],
          [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0],
          [3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0],
          [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0],
          [5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0],
          [6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0]]

weights1 = [[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.5],
          [3.0, 5.0, 5.1, 4.6, 6.5, 7.0, 9.9, 1.7, 7.9, 3.0],
          [0.1, 0.3, 5.0, 6.1, 7.8, 5.1, 9.8, 4.3, 5.0, 3.2],
          [0.3, 5.3, 9.0, 6.3, 7.8, 5.5, 6.1, 3.7, 9.2, 6.8],
          [2.0, 9.6, 4.2, 2.9, 5.3, 6.4, 5.0, 6.9, 0.7, 0.5]]

biases1 = [9.8, 7.9, 8.2, -1.2, -1.3]

weights2 = [[7.1, 7.2, 7.3, 7.4, 7.5],
            [8.1, 8.2, 8.3, 8.4, 8.5],
            [9.1, 9.2, 9.3, 9.4, 9.5]]

biases2 = [-1.1, -2.3, 9.7]

layer1_outputs = num.dot(inputs, num.array(weights1).T) + biases1

layer2_outputs = num.dot(layer1_outputs, num.array(weights2).T) + biases2
print(layer2_outputs)